version: "3.9"
services:
  api:
    build: .
    container_name: student-api
    image: nsahil992/student-api:${VERSION}
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - student_net

  database:
    image: postgres:16
    container_name: student-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./student-data:/var/lib/postgresql/data:rw
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - student_net

networks:
  student_net:

volumes:
  student-data:

