# ----- Database Configmap

apiVersion: v1
kind: ConfigMap
metadata:
  name: student-db-config
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
data:
  POSTGRES_DB: "{{ .Values.db.config.POSTGRES_DB }}"
  POSTGRES_PORT: "{{ .Values.db.config.POSTGRES_PORT}}"

---

# ----- Database Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-db
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: student-db
  template:
    metadata:
      labels:
        app: student-db
    spec:
      nodeSelector:
        type: database
      containers:
        - name: postgres
          image: {{ .Values.db.image }}
          ports:
            - containerPort: {{ .Values.db.port }}
          envFrom:
            - configMapRef:
                name: student-db-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: student-api-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-api-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: student-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: student-data
          persistentVolumeClaim:
            claimName: student-api-pvc

---

# ----- Database Service

apiVersion: v1
kind: Service
metadata:
  name: student-db
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
spec:
  selector:
    app: student-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
