# Persistent Volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: student-api-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/Sahil/Desktop/One2N-SRE-Bootcamp/student-data

---

# Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual