name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'  
  pull_request:
    branches:
      - master  
  workflow_dispatch:

jobs:
  CI:
    name: Continuous Integration (build-test-lint-docker)
    runs-on: [self-hosted]
    env:
      VERSION: ${{ secrets.SEMVER_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Go binary
        run: make build VERSION=${{ env.VERSION }}

      - name: Run unit tests
        run: make test

      - name: Run lint
        run: make lint

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          make docker-build VERSION=${{ env.VERSION }}
          make docker-push VERSION=${{ env.VERSION }}

  cd:
    name: Continuous Deployment (Helm + Git Push)
    runs-on: [self-hosted]
    needs: CI
    if: github.ref == 'refs/heads/master'  
    env:
      VERSION: ${{ secrets.SEMVER_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Helm chart image tag
        run: |
         sed -i '' "s/tag: .*/tag: '${{ env.VERSION }}'/" helm/values.yaml

      - name: Git commit and push
        run: |
          git add helm/values.yaml
          git commit -m "chore: update Helm chart image tag to ${{ env.VERSION }}" || echo "No changes"
          git push origin master